export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SET_USER_TEXT_VALUE = 'SET_USER_TEXT_VALUE';
export const SET_USER_NUMBER_VALUE = 'SET_USER_NUMBER_VALUE';

export default {
  ADD_ITEM,
  EDIT_ITEM,
  DELETE_ITEM,
  SET_USER_TEXT_VALUE,
  SET_USER_NUMBER_VALUE
};